/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorEnvelope {
    #[serde(rename = "error")]
    pub error: Box<models::ApiError>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ApiErrorEnvelope {
    pub fn new(error: models::ApiError, meta: models::Meta) -> ApiErrorEnvelope {
        ApiErrorEnvelope {
            error: Box::new(error),
            meta: Box::new(meta),
        }
    }
}

