/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiVersion {
    #[serde(rename = "apiBaseUrls", skip_serializing_if = "Option::is_none")]
    pub api_base_urls: Option<Vec<String>>,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ApiVersion {
    pub fn new(path: String) -> ApiVersion {
        ApiVersion {
            api_base_urls: None,
            path,
            version: None,
        }
    }
}

