/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthenticatorUpdateWithCurrent : All of the fields on an authenticator that will be updated
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorUpdateWithCurrent {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "currentPassword")]
    pub current_password: String,
}

impl AuthenticatorUpdateWithCurrent {
    /// All of the fields on an authenticator that will be updated
    pub fn new(password: String, username: String, current_password: String) -> AuthenticatorUpdateWithCurrent {
        AuthenticatorUpdateWithCurrent {
            password,
            tags: None,
            username,
            current_password,
        }
    }
}

