/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthPolicyPatch : A Auth Policy resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthPolicyPatch {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<Box<models::AuthPolicyPrimaryPatch>>,
    #[serde(rename = "secondary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secondary: Option<Option<Box<models::AuthPolicySecondaryPatch>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl AuthPolicyPatch {
    /// A Auth Policy resource
    pub fn new() -> AuthPolicyPatch {
        AuthPolicyPatch {
            name: None,
            primary: None,
            secondary: None,
            tags: None,
        }
    }
}

