/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthQueryType {
    #[serde(rename = "MFA")]
    Mfa,
    #[serde(rename = "TOTP")]
    Totp,
    #[serde(rename = "EXT-JWT")]
    ExtJwt,

}

impl std::fmt::Display for AuthQueryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mfa => write!(f, "MFA"),
            Self::Totp => write!(f, "TOTP"),
            Self::ExtJwt => write!(f, "EXT-JWT"),
        }
    }
}

impl Default for AuthQueryType {
    fn default() -> AuthQueryType {
        Self::Mfa
    }
}

