/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthPolicyPrimaryUpdbPatch {
    #[serde(rename = "allowed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<Option<bool>>,
    #[serde(rename = "lockoutDurationMinutes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lockout_duration_minutes: Option<Option<i32>>,
    #[serde(rename = "maxAttempts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_attempts: Option<Option<i32>>,
    #[serde(rename = "minPasswordLength", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_password_length: Option<Option<i32>>,
    #[serde(rename = "requireMixedCase", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_mixed_case: Option<Option<bool>>,
    #[serde(rename = "requireNumberChar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_number_char: Option<Option<bool>>,
    #[serde(rename = "requireSpecialChar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_special_char: Option<Option<bool>>,
}

impl AuthPolicyPrimaryUpdbPatch {
    pub fn new() -> AuthPolicyPrimaryUpdbPatch {
        AuthPolicyPrimaryUpdbPatch {
            allowed: None,
            lockout_duration_minutes: None,
            max_attempts: None,
            min_password_length: None,
            require_mixed_case: None,
            require_number_char: None,
            require_special_char: None,
        }
    }
}

