/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthenticatorPatchWithCurrent : All of the fields on an authenticator that may be updated
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorPatchWithCurrent {
    #[serde(rename = "password", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub password: Option<Option<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub username: Option<Option<String>>,
    #[serde(rename = "currentPassword")]
    pub current_password: String,
}

impl AuthenticatorPatchWithCurrent {
    /// All of the fields on an authenticator that may be updated
    pub fn new(current_password: String) -> AuthenticatorPatchWithCurrent {
        AuthenticatorPatchWithCurrent {
            password: None,
            tags: None,
            username: None,
            current_password,
        }
    }
}

