/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Authenticate : A generic authenticate object meant for use with the /authenticate path. Required fields depend on authentication method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Authenticate {
    /// Specific configuration types that should be returned
    #[serde(rename = "configTypes", skip_serializing_if = "Option::is_none")]
    pub config_types: Option<Vec<String>>,
    #[serde(rename = "envInfo", skip_serializing_if = "Option::is_none")]
    pub env_info: Option<Box<models::EnvInfo>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "sdkInfo", skip_serializing_if = "Option::is_none")]
    pub sdk_info: Option<Box<models::SdkInfo>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl Authenticate {
    /// A generic authenticate object meant for use with the /authenticate path. Required fields depend on authentication method.
    pub fn new() -> Authenticate {
        Authenticate {
            config_types: None,
            env_info: None,
            password: None,
            sdk_info: None,
            username: None,
        }
    }
}

