/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthQueryDetail {
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::MfaFormats>,
    #[serde(rename = "httpMethod", skip_serializing_if = "Option::is_none")]
    pub http_method: Option<String>,
    #[serde(rename = "httpUrl", skip_serializing_if = "Option::is_none")]
    pub http_url: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "isTotpEnrolled", skip_serializing_if = "Option::is_none")]
    pub is_totp_enrolled: Option<bool>,
    #[serde(rename = "maxLength", skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i32>,
    #[serde(rename = "minLength", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i32>,
    #[serde(rename = "provider")]
    pub provider: models::MfaProviders,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    #[serde(rename = "typeId", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<models::AuthQueryType>,
}

impl AuthQueryDetail {
    pub fn new(provider: models::MfaProviders) -> AuthQueryDetail {
        AuthQueryDetail {
            client_id: None,
            format: None,
            http_method: None,
            http_url: None,
            id: None,
            is_totp_enrolled: None,
            max_length: None,
            min_length: None,
            provider,
            scopes: None,
            type_id: None,
        }
    }
}

