/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthenticatorCreate : Creates an authenticator for a specific identity which can be used for API authentication
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorCreate {
    /// The client certificate the identity will login with. Used only for method='cert'
    #[serde(rename = "certPem", skip_serializing_if = "Option::is_none")]
    pub cert_pem: Option<String>,
    /// The id of an existing identity that will be assigned this authenticator
    #[serde(rename = "identityId")]
    pub identity_id: String,
    /// The type of authenticator to create; which will dictate which properties on this object are required.
    #[serde(rename = "method")]
    pub method: String,
    /// The password the identity will login with. Used only for method='updb'
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    /// The username that the identity will login with. Used only for method='updb'
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl AuthenticatorCreate {
    /// Creates an authenticator for a specific identity which can be used for API authentication
    pub fn new(identity_id: String, method: String) -> AuthenticatorCreate {
        AuthenticatorCreate {
            cert_pem: None,
            identity_id,
            method,
            password: None,
            tags: None,
            username: None,
        }
    }
}

