/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CaDetail : A Certificate Authority (CA) resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "certPem")]
    pub cert_pem: String,
    #[serde(rename = "externalIdClaim", skip_serializing_if = "Option::is_none")]
    pub external_id_claim: Option<Box<models::ExternalIdClaim>>,
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    #[serde(rename = "identityNameFormat")]
    pub identity_name_format: String,
    #[serde(rename = "identityRoles")]
    pub identity_roles: Vec<String>,
    #[serde(rename = "isAuthEnabled")]
    pub is_auth_enabled: bool,
    #[serde(rename = "isAutoCaEnrollmentEnabled")]
    pub is_auto_ca_enrollment_enabled: bool,
    #[serde(rename = "isOttCaEnrollmentEnabled")]
    pub is_ott_ca_enrollment_enabled: bool,
    #[serde(rename = "isVerified")]
    pub is_verified: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "verificationToken", skip_serializing_if = "Option::is_none")]
    pub verification_token: Option<uuid::Uuid>,
}

impl CaDetail {
    /// A Certificate Authority (CA) resource
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, cert_pem: String, fingerprint: String, identity_name_format: String, identity_roles: Vec<String>, is_auth_enabled: bool, is_auto_ca_enrollment_enabled: bool, is_ott_ca_enrollment_enabled: bool, is_verified: bool, name: String) -> CaDetail {
        CaDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            cert_pem,
            external_id_claim: None,
            fingerprint,
            identity_name_format,
            identity_roles,
            is_auth_enabled,
            is_auto_ca_enrollment_enabled,
            is_ott_ca_enrollment_enabled,
            is_verified,
            name,
            verification_token: None,
        }
    }
}

