/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Capabilities {
    #[serde(rename = "OIDC_AUTH")]
    OidcAuth,
    #[serde(rename = "HA_CONTROLLER")]
    HaController,

}

impl std::fmt::Display for Capabilities {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OidcAuth => write!(f, "OIDC_AUTH"),
            Self::HaController => write!(f, "HA_CONTROLLER"),
        }
    }
}

impl Default for Capabilities {
    fn default() -> Capabilities {
        Self::OidcAuth
    }
}

