/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTypeDetail : A config-type resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTypeDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON schema to enforce configuration against
    #[serde(rename = "schema")]
    pub schema: std::collections::HashMap<String, serde_json::Value>,
}

impl ConfigTypeDetail {
    /// A config-type resource
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, name: String, schema: std::collections::HashMap<String, serde_json::Value>) -> ConfigTypeDetail {
        ConfigTypeDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            name,
            schema,
        }
    }
}

