/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTypeCreate : A config-type create object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTypeCreate {
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON schema to enforce configuration against
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl ConfigTypeCreate {
    /// A config-type create object
    pub fn new(name: String) -> ConfigTypeCreate {
        ConfigTypeCreate {
            name,
            schema: None,
            tags: None,
        }
    }
}

