/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigUpdate : A config update object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigUpdate {
    /// Data payload is defined by the schema of the config-type defined in the type parameter
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl ConfigUpdate {
    /// A config update object
    pub fn new(data: std::collections::HashMap<String, serde_json::Value>, name: String) -> ConfigUpdate {
        ConfigUpdate {
            data,
            name,
            tags: None,
        }
    }
}

