/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigDetail : A config resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "configType")]
    pub config_type: Box<models::EntityRef>,
    #[serde(rename = "configTypeId")]
    pub config_type_id: String,
    /// The data section of a config is based on the schema of its type
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "name")]
    pub name: String,
}

impl ConfigDetail {
    /// A config resource
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, config_type: models::EntityRef, config_type_id: String, data: serde_json::Value, name: String) -> ConfigDetail {
        ConfigDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            config_type: Box::new(config_type),
            config_type_id,
            data,
            name,
        }
    }
}

