/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControllerSettingCreate {
    #[serde(rename = "oidc", skip_serializing_if = "Option::is_none")]
    pub oidc: Option<Box<models::ControllerSettingsOidc>>,
    #[serde(rename = "controllerId")]
    pub controller_id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl ControllerSettingCreate {
    pub fn new(controller_id: String) -> ControllerSettingCreate {
        ControllerSettingCreate {
            oidc: None,
            controller_id,
            tags: None,
        }
    }
}

