/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControllerSettingsOidc {
    #[serde(rename = "postLogoutUris", skip_serializing_if = "Option::is_none")]
    pub post_logout_uris: Option<Vec<String>>,
    #[serde(rename = "redirectUris", skip_serializing_if = "Option::is_none")]
    pub redirect_uris: Option<Vec<String>>,
}

impl ControllerSettingsOidc {
    pub fn new() -> ControllerSettingsOidc {
        ControllerSettingsOidc {
            post_logout_uris: None,
            redirect_uris: None,
        }
    }
}

