/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLocation {
    /// A map of named links
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<std::collections::HashMap<String, models::Link>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CreateLocation {
    pub fn new() -> CreateLocation {
        CreateLocation {
            _links: None,
            id: None,
        }
    }
}

