/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CurrentApiSessionDetail : An API Session object for the current API session
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentApiSessionDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "authQueries")]
    pub auth_queries: Vec<models::AuthQueryDetail>,
    #[serde(rename = "authenticatorId")]
    pub authenticator_id: String,
    #[serde(rename = "cachedLastActivityAt", skip_serializing_if = "Option::is_none")]
    pub cached_last_activity_at: Option<String>,
    #[serde(rename = "configTypes")]
    pub config_types: Vec<String>,
    #[serde(rename = "identity")]
    pub identity: Box<models::EntityRef>,
    #[serde(rename = "identityId")]
    pub identity_id: String,
    #[serde(rename = "improperClientCertChain", skip_serializing_if = "Option::is_none")]
    pub improper_client_cert_chain: Option<bool>,
    #[serde(rename = "ipAddress")]
    pub ip_address: String,
    #[serde(rename = "isCertExtendRequested", skip_serializing_if = "Option::is_none")]
    pub is_cert_extend_requested: Option<bool>,
    #[serde(rename = "isCertExtendable")]
    pub is_cert_extendable: bool,
    #[serde(rename = "isCertKeyRollRequested", skip_serializing_if = "Option::is_none")]
    pub is_cert_key_roll_requested: Option<bool>,
    #[serde(rename = "isMfaComplete")]
    pub is_mfa_complete: bool,
    #[serde(rename = "isMfaRequired")]
    pub is_mfa_required: bool,
    #[serde(rename = "lastActivityAt", skip_serializing_if = "Option::is_none")]
    pub last_activity_at: Option<String>,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "expirationSeconds")]
    pub expiration_seconds: i32,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl CurrentApiSessionDetail {
    /// An API Session object for the current API session
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, auth_queries: Vec<models::AuthQueryDetail>, authenticator_id: String, config_types: Vec<String>, identity: models::EntityRef, identity_id: String, ip_address: String, is_cert_extendable: bool, is_mfa_complete: bool, is_mfa_required: bool, token: String, expiration_seconds: i32, expires_at: String) -> CurrentApiSessionDetail {
        CurrentApiSessionDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            auth_queries,
            authenticator_id,
            cached_last_activity_at: None,
            config_types,
            identity: Box::new(identity),
            identity_id,
            improper_client_cert_chain: None,
            ip_address,
            is_cert_extend_requested: None,
            is_cert_extendable,
            is_cert_key_roll_requested: None,
            is_mfa_complete,
            is_mfa_required,
            last_activity_at: None,
            token,
            expiration_seconds,
            expires_at,
        }
    }
}

