/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailControllerSettingEnvelope {
    #[serde(rename = "data")]
    pub data: Box<models::ControllerSettingDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl DetailControllerSettingEnvelope {
    pub fn new(data: models::ControllerSettingDetail, meta: models::Meta) -> DetailControllerSettingEnvelope {
        DetailControllerSettingEnvelope {
            data: Box::new(data),
            meta: Box::new(meta),
        }
    }
}

