/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailMfa {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "isVerified")]
    pub is_verified: bool,
    /// Not provided if MFA verification has been completed
    #[serde(rename = "provisioningUrl", skip_serializing_if = "Option::is_none")]
    pub provisioning_url: Option<String>,
    /// Not provided if MFA verification has been completed
    #[serde(rename = "recoveryCodes", skip_serializing_if = "Option::is_none")]
    pub recovery_codes: Option<Vec<String>>,
}

impl DetailMfa {
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, is_verified: bool) -> DetailMfa {
        DetailMfa {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            is_verified,
            provisioning_url: None,
            recovery_codes: None,
        }
    }
}

