/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DialBind {
    #[serde(rename = "Dial")]
    Dial,
    #[serde(rename = "Bind")]
    Bind,
    #[serde(rename = "Invalid")]
    Invalid,

}

impl std::fmt::Display for DialBind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dial => write!(f, "Dial"),
            Self::Bind => write!(f, "Bind"),
            Self::Invalid => write!(f, "Invalid"),
        }
    }
}

impl Default for DialBind {
    fn default() -> DialBind {
        Self::Dial
    }
}

