/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeRouterPolicyDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "edgeRouterRoles")]
    pub edge_router_roles: Vec<String>,
    #[serde(rename = "edgeRouterRolesDisplay")]
    pub edge_router_roles_display: Vec<models::NamedRole>,
    #[serde(rename = "identityRoles")]
    pub identity_roles: Vec<String>,
    #[serde(rename = "identityRolesDisplay")]
    pub identity_roles_display: Vec<models::NamedRole>,
    #[serde(rename = "isSystem")]
    pub is_system: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "semantic")]
    pub semantic: models::Semantic,
}

impl EdgeRouterPolicyDetail {
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, edge_router_roles: Vec<String>, edge_router_roles_display: Vec<models::NamedRole>, identity_roles: Vec<String>, identity_roles_display: Vec<models::NamedRole>, is_system: bool, name: String, semantic: models::Semantic) -> EdgeRouterPolicyDetail {
        EdgeRouterPolicyDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            edge_router_roles,
            edge_router_roles_display,
            identity_roles,
            identity_roles_display,
            is_system,
            name,
            semantic,
        }
    }
}

