/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeRouterPolicyUpdate {
    #[serde(rename = "edgeRouterRoles", skip_serializing_if = "Option::is_none")]
    pub edge_router_roles: Option<Vec<String>>,
    #[serde(rename = "identityRoles", skip_serializing_if = "Option::is_none")]
    pub identity_roles: Option<Vec<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "semantic")]
    pub semantic: models::Semantic,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl EdgeRouterPolicyUpdate {
    pub fn new(name: String, semantic: models::Semantic) -> EdgeRouterPolicyUpdate {
        EdgeRouterPolicyUpdate {
            edge_router_roles: None,
            identity_roles: None,
            name,
            semantic,
            tags: None,
        }
    }
}

