/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalIdClaim {
    #[serde(rename = "index", deserialize_with = "Option::deserialize")]
    pub index: Option<i32>,
    #[serde(rename = "location", deserialize_with = "Option::deserialize")]
    pub location: Option<Location>,
    #[serde(rename = "matcher", deserialize_with = "Option::deserialize")]
    pub matcher: Option<Matcher>,
    #[serde(rename = "matcherCriteria", deserialize_with = "Option::deserialize")]
    pub matcher_criteria: Option<String>,
    #[serde(rename = "parser", deserialize_with = "Option::deserialize")]
    pub parser: Option<Parser>,
    #[serde(rename = "parserCriteria", deserialize_with = "Option::deserialize")]
    pub parser_criteria: Option<String>,
}

impl ExternalIdClaim {
    pub fn new(index: Option<i32>, location: Option<Location>, matcher: Option<Matcher>, matcher_criteria: Option<String>, parser: Option<Parser>, parser_criteria: Option<String>) -> ExternalIdClaim {
        ExternalIdClaim {
            index,
            location,
            matcher,
            matcher_criteria,
            parser,
            parser_criteria,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Location {
    #[serde(rename = "COMMON_NAME")]
    CommonName,
    #[serde(rename = "SAN_URI")]
    SanUri,
    #[serde(rename = "SAN_EMAIL")]
    SanEmail,
}

impl Default for Location {
    fn default() -> Location {
        Self::CommonName
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Matcher {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "PREFIX")]
    Prefix,
    #[serde(rename = "SUFFIX")]
    Suffix,
    #[serde(rename = "SCHEME")]
    Scheme,
}

impl Default for Matcher {
    fn default() -> Matcher {
        Self::All
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Parser {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "SPLIT")]
    Split,
}

impl Default for Parser {
    fn default() -> Parser {
        Self::None
    }
}

