/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIdentityPolicyAdviceEnvelope {
    #[serde(rename = "data")]
    pub data: Box<models::PolicyAdvice>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl GetIdentityPolicyAdviceEnvelope {
    pub fn new(data: models::PolicyAdvice, meta: models::Meta) -> GetIdentityPolicyAdviceEnvelope {
        GetIdentityPolicyAdviceEnvelope {
            data: Box::new(data),
            meta: Box::new(meta),
        }
    }
}

