/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Interface : A resource describing a network interface
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Interface {
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<String>>,
    #[serde(rename = "hardwareAddress")]
    pub hardware_address: String,
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "isBroadcast")]
    pub is_broadcast: bool,
    #[serde(rename = "isLoopback")]
    pub is_loopback: bool,
    #[serde(rename = "isMulticast")]
    pub is_multicast: bool,
    #[serde(rename = "isRunning")]
    pub is_running: bool,
    #[serde(rename = "isUp")]
    pub is_up: bool,
    #[serde(rename = "mtu")]
    pub mtu: i32,
    #[serde(rename = "name")]
    pub name: String,
}

impl Interface {
    /// A resource describing a network interface
    pub fn new(hardware_address: String, index: i32, is_broadcast: bool, is_loopback: bool, is_multicast: bool, is_running: bool, is_up: bool, mtu: i32, name: String) -> Interface {
        Interface {
            addresses: None,
            hardware_address,
            index,
            is_broadcast,
            is_loopback,
            is_multicast,
            is_running,
            is_up,
            mtu,
            name,
        }
    }
}

