/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSummaryCountsEnvelope {
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, i32>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListSummaryCountsEnvelope {
    pub fn new(data: std::collections::HashMap<String, i32>, meta: models::Meta) -> ListSummaryCountsEnvelope {
        ListSummaryCountsEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

