/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAuthenticatorsEnvelope {
    /// An array of authenticator resources
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::AuthenticatorDetail>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::Meta>>,
}

impl ListAuthenticatorsEnvelope {
    pub fn new() -> ListAuthenticatorsEnvelope {
        ListAuthenticatorsEnvelope {
            data: None,
            meta: None,
        }
    }
}

