/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRoutersEnvelope {
    #[serde(rename = "data")]
    pub data: Vec<models::RouterDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListRoutersEnvelope {
    pub fn new(data: Vec<models::RouterDetail>, meta: models::Meta) -> ListRoutersEnvelope {
        ListRoutersEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

