/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListControllersEnvelope {
    /// An array of controller resources
    #[serde(rename = "data")]
    pub data: Vec<models::ControllerDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListControllersEnvelope {
    pub fn new(data: Vec<models::ControllerDetail>, meta: models::Meta) -> ListControllersEnvelope {
        ListControllersEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

