/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServicePoliciesEnvelope {
    #[serde(rename = "data")]
    pub data: Vec<models::ServicePolicyDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListServicePoliciesEnvelope {
    pub fn new(data: Vec<models::ServicePolicyDetail>, meta: models::Meta) -> ListServicePoliciesEnvelope {
        ListServicePoliciesEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

