/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListConfigsEnvelope {
    /// An array of config resources
    #[serde(rename = "data")]
    pub data: Vec<models::ConfigDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListConfigsEnvelope {
    pub fn new(data: Vec<models::ConfigDetail>, meta: models::Meta) -> ListConfigsEnvelope {
        ListConfigsEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

