/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServiceEdgeRouterPoliciesEnvelope {
    #[serde(rename = "data")]
    pub data: Vec<models::ServiceEdgeRouterPolicyDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListServiceEdgeRouterPoliciesEnvelope {
    pub fn new(data: Vec<models::ServiceEdgeRouterPolicyDetail>, meta: models::Meta) -> ListServiceEdgeRouterPoliciesEnvelope {
        ListServiceEdgeRouterPoliciesEnvelope {
            data,
            meta: Box::new(meta),
        }
    }
}

