/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaFormats {
    #[serde(rename = "numeric")]
    Numeric,
    #[serde(rename = "alpha")]
    Alpha,
    #[serde(rename = "alphaNumeric")]
    AlphaNumeric,

}

impl std::fmt::Display for MfaFormats {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Numeric => write!(f, "numeric"),
            Self::Alpha => write!(f, "alpha"),
            Self::AlphaNumeric => write!(f, "alphaNumeric"),
        }
    }
}

impl Default for MfaFormats {
    fn default() -> MfaFormats {
        Self::Numeric
    }
}

