/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaProviders {
    #[serde(rename = "ziti")]
    Ziti,
    #[serde(rename = "url")]
    Url,

}

impl std::fmt::Display for MfaProviders {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ziti => write!(f, "ziti"),
            Self::Url => write!(f, "url"),
        }
    }
}

impl Default for MfaProviders {
    fn default() -> MfaProviders {
        Self::Ziti
    }
}

