/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetworkJwt : A network JWT
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkJwt {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl NetworkJwt {
    /// A network JWT
    pub fn new(name: String, token: String) -> NetworkJwt {
        NetworkJwt {
            name,
            token,
        }
    }
}

