/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperatingSystem {
    #[serde(rename = "type")]
    pub r#type: models::OsType,
    #[serde(rename = "versions")]
    pub versions: Vec<String>,
}

impl OperatingSystem {
    pub fn new(r#type: models::OsType, versions: Vec<String>) -> OperatingSystem {
        OperatingSystem {
            r#type,
            versions,
        }
    }
}

