/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    #[serde(rename = "limit")]
    pub limit: f64,
    #[serde(rename = "offset")]
    pub offset: f64,
    #[serde(rename = "totalCount")]
    pub total_count: f64,
}

impl Pagination {
    pub fn new(limit: f64, offset: f64, total_count: f64) -> Pagination {
        Pagination {
            limit,
            offset,
            total_count,
        }
    }
}

