/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "postureCheckType")]
pub enum PostureCheckFailure {
    #[serde(rename="postureCheckFailureDomain")]
    PostureCheckFailureDomain {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
    #[serde(rename="postureCheckFailureMacAddress")]
    PostureCheckFailureMacAddress {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
    #[serde(rename="postureCheckFailureMfa")]
    PostureCheckFailureMfa {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
    #[serde(rename="postureCheckFailureOperatingSystem")]
    PostureCheckFailureOperatingSystem {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
    #[serde(rename="postureCheckFailureProcess")]
    PostureCheckFailureProcess {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
    #[serde(rename="postureCheckFailureProcessMulti")]
    PostureCheckFailureProcessMulti {
        #[serde(rename = "postureCheckId")]
        posture_check_id: String,
        #[serde(rename = "postureCheckName")]
        posture_check_name: String,
    },
}

impl Default for PostureCheckFailure {
    fn default() -> Self {
        Self::PostureCheckFailureDomain {
            posture_check_id: Default::default(),
            posture_check_name: Default::default(),
        }
        
    }
}


