/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "typeId")]
pub enum PostureCheckPatch {
    #[serde(rename="postureCheckDomainPatch")]
    PostureCheckDomainPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
    #[serde(rename="postureCheckMacAddressPatch")]
    PostureCheckMacAddressPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
    #[serde(rename="postureCheckMfaPatch")]
    PostureCheckMfaPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
    #[serde(rename="postureCheckOperatingSystemPatch")]
    PostureCheckOperatingSystemPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
    #[serde(rename="postureCheckProcessMultiPatch")]
    PostureCheckProcessMultiPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
    #[serde(rename="postureCheckProcessPatch")]
    PostureCheckProcessPatch {
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        /// A set of strings used to loosly couple this resource to policies
        #[serde(rename = "roleAttributes", skip_serializing_if = "Option::is_none")]
        role_attributes: Option<Vec<String>>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Box<models::Tags>>,
    },
}

impl Default for PostureCheckPatch {
    fn default() -> Self {
        Self::PostureCheckDomainPatch {
            name: Default::default(),
            role_attributes: Default::default(),
            tags: Default::default(),
        }
        
    }
}


