/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckFailureMfa {
    #[serde(rename = "postureCheckId")]
    pub posture_check_id: String,
    #[serde(rename = "postureCheckName")]
    pub posture_check_name: String,
    #[serde(rename = "postureCheckType")]
    pub posture_check_type: String,
    #[serde(rename = "actualValue")]
    pub actual_value: Box<models::PostureChecksFailureMfaValues>,
    #[serde(rename = "criteria")]
    pub criteria: Box<models::PostureChecksFailureMfaCriteria>,
    #[serde(rename = "expectedValue")]
    pub expected_value: Box<models::PostureChecksFailureMfaValues>,
}

impl PostureCheckFailureMfa {
    pub fn new(posture_check_id: String, posture_check_name: String, posture_check_type: String, actual_value: models::PostureChecksFailureMfaValues, criteria: models::PostureChecksFailureMfaCriteria, expected_value: models::PostureChecksFailureMfaValues) -> PostureCheckFailureMfa {
        PostureCheckFailureMfa {
            posture_check_id,
            posture_check_name,
            posture_check_type,
            actual_value: Box::new(actual_value),
            criteria: Box::new(criteria),
            expected_value: Box::new(expected_value),
        }
    }
}

