/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckMfaUpdate {
    #[serde(rename = "name")]
    pub name: String,
    /// A set of strings used to loosely couple this resource to policies
    #[serde(rename = "roleAttributes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_attributes: Option<Option<Vec<String>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "typeId", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<models::PostureCheckType>,
    #[serde(rename = "ignoreLegacyEndpoints", skip_serializing_if = "Option::is_none")]
    pub ignore_legacy_endpoints: Option<bool>,
    #[serde(rename = "promptOnUnlock", skip_serializing_if = "Option::is_none")]
    pub prompt_on_unlock: Option<bool>,
    #[serde(rename = "promptOnWake", skip_serializing_if = "Option::is_none")]
    pub prompt_on_wake: Option<bool>,
    #[serde(rename = "timeoutSeconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
}

impl PostureCheckMfaUpdate {
    pub fn new(name: String) -> PostureCheckMfaUpdate {
        PostureCheckMfaUpdate {
            name,
            role_attributes: None,
            tags: None,
            type_id: None,
            ignore_legacy_endpoints: None,
            prompt_on_unlock: None,
            prompt_on_wake: None,
            timeout_seconds: None,
        }
    }
}

