/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckFailureProcessMulti {
    #[serde(rename = "postureCheckId")]
    pub posture_check_id: String,
    #[serde(rename = "postureCheckName")]
    pub posture_check_name: String,
    #[serde(rename = "postureCheckType")]
    pub posture_check_type: String,
    #[serde(rename = "actualValue")]
    pub actual_value: Vec<models::PostureCheckFailureProcessActual>,
    #[serde(rename = "expectedValue")]
    pub expected_value: Vec<models::ProcessMulti>,
    #[serde(rename = "semantic")]
    pub semantic: models::Semantic,
}

impl PostureCheckFailureProcessMulti {
    pub fn new(posture_check_id: String, posture_check_name: String, posture_check_type: String, actual_value: Vec<models::PostureCheckFailureProcessActual>, expected_value: Vec<models::ProcessMulti>, semantic: models::Semantic) -> PostureCheckFailureProcessMulti {
        PostureCheckFailureProcessMulti {
            posture_check_id,
            posture_check_name,
            posture_check_type,
            actual_value,
            expected_value,
            semantic,
        }
    }
}

