/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckProcessMultiPatch {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A set of strings used to loosely couple this resource to policies
    #[serde(rename = "roleAttributes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_attributes: Option<Option<Vec<String>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "typeId")]
    pub type_id: models::PostureCheckType,
    #[serde(rename = "processes", skip_serializing_if = "Option::is_none")]
    pub processes: Option<Vec<models::ProcessMulti>>,
    #[serde(rename = "semantic", skip_serializing_if = "Option::is_none")]
    pub semantic: Option<models::Semantic>,
}

impl PostureCheckProcessMultiPatch {
    pub fn new(type_id: models::PostureCheckType) -> PostureCheckProcessMultiPatch {
        PostureCheckProcessMultiPatch {
            name: None,
            role_attributes: None,
            tags: None,
            type_id,
            processes: None,
            semantic: None,
        }
    }
}

