/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckProcessMultiDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// A set of strings used to loosly couple this resource to policies
    #[serde(rename = "roleAttributes", deserialize_with = "Option::deserialize")]
    pub role_attributes: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Box<models::Tags>,
    #[serde(rename = "typeId")]
    pub type_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "processes")]
    pub processes: Vec<models::ProcessMulti>,
    #[serde(rename = "semantic")]
    pub semantic: models::Semantic,
}

impl PostureCheckProcessMultiDetail {
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, name: String, role_attributes: Option<Vec<String>>, tags: models::Tags, type_id: String, updated_at: String, version: i32, processes: Vec<models::ProcessMulti>, semantic: models::Semantic) -> PostureCheckProcessMultiDetail {
        PostureCheckProcessMultiDetail {
            _links,
            created_at,
            id,
            name,
            role_attributes,
            tags: Box::new(tags),
            type_id,
            updated_at,
            version,
            processes,
            semantic,
        }
    }
}

