/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckFailureProcessActual {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "isRunning")]
    pub is_running: bool,
    #[serde(rename = "osType", skip_serializing_if = "Option::is_none")]
    pub os_type: Option<models::OsType>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "signerFingerprints")]
    pub signer_fingerprints: Vec<String>,
}

impl PostureCheckFailureProcessActual {
    pub fn new(hash: String, is_running: bool, signer_fingerprints: Vec<String>) -> PostureCheckFailureProcessActual {
        PostureCheckFailureProcessActual {
            hash,
            is_running,
            os_type: None,
            path: None,
            signer_fingerprints,
        }
    }
}

