/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckFailureOperatingSystemActual {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl PostureCheckFailureOperatingSystemActual {
    pub fn new(r#type: String, version: String) -> PostureCheckFailureOperatingSystemActual {
        PostureCheckFailureOperatingSystemActual {
            r#type,
            version,
        }
    }
}

