/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckMfaPatch {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A set of strings used to loosly couple this resource to policies
    #[serde(rename = "roleAttributes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_attributes: Option<Option<Vec<String>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "typeId")]
    pub type_id: models::PostureCheckType,
    #[serde(rename = "ignoreLegacyEndpoints", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ignore_legacy_endpoints: Option<Option<bool>>,
    #[serde(rename = "promptOnUnlock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt_on_unlock: Option<Option<bool>>,
    #[serde(rename = "promptOnWake", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt_on_wake: Option<Option<bool>>,
    #[serde(rename = "timeoutSeconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<Option<i32>>,
}

impl PostureCheckMfaPatch {
    pub fn new(type_id: models::PostureCheckType) -> PostureCheckMfaPatch {
        PostureCheckMfaPatch {
            name: None,
            role_attributes: None,
            tags: None,
            type_id,
            ignore_legacy_endpoints: None,
            prompt_on_unlock: None,
            prompt_on_wake: None,
            timeout_seconds: None,
        }
    }
}

