/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureDataOs {
    #[serde(rename = "lastUpdatedAt")]
    pub last_updated_at: String,
    #[serde(rename = "postureCheckId")]
    pub posture_check_id: String,
    #[serde(rename = "timedOut")]
    pub timed_out: bool,
    #[serde(rename = "build")]
    pub build: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl PostureDataOs {
    pub fn new(last_updated_at: String, posture_check_id: String, timed_out: bool, build: String, r#type: String, version: String) -> PostureDataOs {
        PostureDataOs {
            last_updated_at,
            posture_check_id,
            timed_out,
            build,
            r#type,
            version,
        }
    }
}

