/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureData {
    #[serde(rename = "apiSessionPostureData")]
    pub api_session_posture_data: std::collections::HashMap<String, models::ApiSessionPostureData>,
    #[serde(rename = "domain")]
    pub domain: Box<models::PostureDataDomain>,
    #[serde(rename = "mac")]
    pub mac: Box<models::PostureDataMac>,
    #[serde(rename = "os")]
    pub os: Box<models::PostureDataOs>,
    #[serde(rename = "processes")]
    pub processes: Vec<models::PostureDataProcess>,
}

impl PostureData {
    pub fn new(api_session_posture_data: std::collections::HashMap<String, models::ApiSessionPostureData>, domain: models::PostureDataDomain, mac: models::PostureDataMac, os: models::PostureDataOs, processes: Vec<models::PostureDataProcess>) -> PostureData {
        PostureData {
            api_session_posture_data,
            domain: Box::new(domain),
            mac: Box::new(mac),
            os: Box::new(os),
            processes,
        }
    }
}

