/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckFailureOperatingSystem {
    #[serde(rename = "postureCheckId")]
    pub posture_check_id: String,
    #[serde(rename = "postureCheckName")]
    pub posture_check_name: String,
    #[serde(rename = "postureCheckType")]
    pub posture_check_type: String,
    #[serde(rename = "actualValue")]
    pub actual_value: Box<models::PostureCheckFailureOperatingSystemActual>,
    #[serde(rename = "expectedValue")]
    pub expected_value: Vec<models::OperatingSystem>,
}

impl PostureCheckFailureOperatingSystem {
    pub fn new(posture_check_id: String, posture_check_name: String, posture_check_type: String, actual_value: models::PostureCheckFailureOperatingSystemActual, expected_value: Vec<models::OperatingSystem>) -> PostureCheckFailureOperatingSystem {
        PostureCheckFailureOperatingSystem {
            posture_check_id,
            posture_check_name,
            posture_check_type,
            actual_value: Box::new(actual_value),
            expected_value,
        }
    }
}

