/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureCheckMfaProperties {
    #[serde(rename = "ignoreLegacyEndpoints", skip_serializing_if = "Option::is_none")]
    pub ignore_legacy_endpoints: Option<bool>,
    #[serde(rename = "promptOnUnlock", skip_serializing_if = "Option::is_none")]
    pub prompt_on_unlock: Option<bool>,
    #[serde(rename = "promptOnWake", skip_serializing_if = "Option::is_none")]
    pub prompt_on_wake: Option<bool>,
    #[serde(rename = "timeoutSeconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
}

impl PostureCheckMfaProperties {
    pub fn new() -> PostureCheckMfaProperties {
        PostureCheckMfaProperties {
            ignore_legacy_endpoints: None,
            prompt_on_unlock: None,
            prompt_on_wake: None,
            timeout_seconds: None,
        }
    }
}

