/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PostureCheckType {
    #[serde(rename = "OS")]
    Os,
    #[serde(rename = "PROCESS")]
    Process,
    #[serde(rename = "DOMAIN")]
    Domain,
    #[serde(rename = "MAC")]
    Mac,
    #[serde(rename = "MFA")]
    Mfa,
    #[serde(rename = "PROCESS_MULTI")]
    ProcessMulti,

}

impl std::fmt::Display for PostureCheckType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Os => write!(f, "OS"),
            Self::Process => write!(f, "PROCESS"),
            Self::Domain => write!(f, "DOMAIN"),
            Self::Mac => write!(f, "MAC"),
            Self::Mfa => write!(f, "MFA"),
            Self::ProcessMulti => write!(f, "PROCESS_MULTI"),
        }
    }
}

impl Default for PostureCheckType {
    fn default() -> PostureCheckType {
        Self::Os
    }
}

