/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostureDataProcess {
    #[serde(rename = "lastUpdatedAt")]
    pub last_updated_at: String,
    #[serde(rename = "postureCheckId")]
    pub posture_check_id: String,
    #[serde(rename = "timedOut")]
    pub timed_out: bool,
    #[serde(rename = "binaryHash", skip_serializing_if = "Option::is_none")]
    pub binary_hash: Option<String>,
    #[serde(rename = "isRunning", skip_serializing_if = "Option::is_none")]
    pub is_running: Option<bool>,
    #[serde(rename = "signerFingerprints", skip_serializing_if = "Option::is_none")]
    pub signer_fingerprints: Option<Vec<String>>,
}

impl PostureDataProcess {
    pub fn new(last_updated_at: String, posture_check_id: String, timed_out: bool) -> PostureDataProcess {
        PostureDataProcess {
            last_updated_at,
            posture_check_id,
            timed_out,
            binary_hash: None,
            is_running: None,
            signer_fingerprints: None,
        }
    }
}

