/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Process {
    #[serde(rename = "hashes", skip_serializing_if = "Option::is_none")]
    pub hashes: Option<Vec<String>>,
    #[serde(rename = "osType")]
    pub os_type: models::OsType,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "signerFingerprint", skip_serializing_if = "Option::is_none")]
    pub signer_fingerprint: Option<String>,
}

impl Process {
    pub fn new(os_type: models::OsType, path: String) -> Process {
        Process {
            hashes: None,
            os_type,
            path,
            signer_fingerprint: None,
        }
    }
}

