/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReEnroll {
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl ReEnroll {
    pub fn new(expires_at: String) -> ReEnroll {
        ReEnroll {
            expires_at,
        }
    }
}

