/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestExtendAuthenticator {
    #[serde(rename = "rollKeys", skip_serializing_if = "Option::is_none")]
    pub roll_keys: Option<bool>,
}

impl RequestExtendAuthenticator {
    pub fn new() -> RequestExtendAuthenticator {
        RequestExtendAuthenticator {
            roll_keys: None,
        }
    }
}

