/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouterEntityRef {
    /// A map of named links
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<std::collections::HashMap<String, models::Link>>,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isOnline")]
    pub is_online: bool,
}

impl RouterEntityRef {
    pub fn new(is_online: bool) -> RouterEntityRef {
        RouterEntityRef {
            _links: None,
            entity: None,
            id: None,
            name: None,
            is_online,
        }
    }
}

