/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Semantic {
    #[serde(rename = "AllOf")]
    AllOf,
    #[serde(rename = "AnyOf")]
    AnyOf,

}

impl std::fmt::Display for Semantic {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AllOf => write!(f, "AllOf"),
            Self::AnyOf => write!(f, "AnyOf"),
        }
    }
}

impl Default for Semantic {
    fn default() -> Semantic {
        Self::AllOf
    }
}

