/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceConfigDetail {
    #[serde(rename = "config")]
    pub config: Box<models::EntityRef>,
    #[serde(rename = "configId")]
    pub config_id: String,
    #[serde(rename = "service")]
    pub service: Box<models::EntityRef>,
    #[serde(rename = "serviceId")]
    pub service_id: String,
}

impl ServiceConfigDetail {
    pub fn new(config: models::EntityRef, config_id: String, service: models::EntityRef, service_id: String) -> ServiceConfigDetail {
        ServiceConfigDetail {
            config: Box::new(config),
            config_id,
            service: Box::new(service),
            service_id,
        }
    }
}

