/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceEdgeRouterPolicyPatch {
    #[serde(rename = "edgeRouterRoles", skip_serializing_if = "Option::is_none")]
    pub edge_router_roles: Option<Vec<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "semantic", skip_serializing_if = "Option::is_none")]
    pub semantic: Option<models::Semantic>,
    #[serde(rename = "serviceRoles", skip_serializing_if = "Option::is_none")]
    pub service_roles: Option<Vec<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl ServiceEdgeRouterPolicyPatch {
    pub fn new() -> ServiceEdgeRouterPolicyPatch {
        ServiceEdgeRouterPolicyPatch {
            edge_router_roles: None,
            name: None,
            semantic: None,
            service_roles: None,
            tags: None,
        }
    }
}

