/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "apiSession")]
    pub api_session: Box<models::EntityRef>,
    #[serde(rename = "apiSessionId")]
    pub api_session_id: String,
    #[serde(rename = "edgeRouters")]
    pub edge_routers: Vec<models::SessionEdgeRouter>,
    #[serde(rename = "identityId")]
    pub identity_id: String,
    #[serde(rename = "service")]
    pub service: Box<models::EntityRef>,
    #[serde(rename = "serviceId")]
    pub service_id: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "type")]
    pub r#type: models::DialBind,
}

impl SessionDetail {
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, api_session: models::EntityRef, api_session_id: String, edge_routers: Vec<models::SessionEdgeRouter>, identity_id: String, service: models::EntityRef, service_id: String, token: String, r#type: models::DialBind) -> SessionDetail {
        SessionDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            api_session: Box::new(api_session),
            api_session_id,
            edge_routers,
            identity_id,
            service: Box::new(service),
            service_id,
            token,
            r#type,
        }
    }
}

