/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerminatorDetail {
    /// A map of named links
    #[serde(rename = "_links")]
    pub _links: std::collections::HashMap<String, models::Link>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "binding")]
    pub binding: String,
    #[serde(rename = "cost")]
    pub cost: i32,
    #[serde(rename = "dynamicCost")]
    pub dynamic_cost: i32,
    #[serde(rename = "identity")]
    pub identity: String,
    #[serde(rename = "precedence")]
    pub precedence: models::TerminatorPrecedence,
    #[serde(rename = "router")]
    pub router: Box<models::EntityRef>,
    #[serde(rename = "routerId")]
    pub router_id: String,
    #[serde(rename = "service")]
    pub service: Box<models::EntityRef>,
    #[serde(rename = "serviceId")]
    pub service_id: String,
}

impl TerminatorDetail {
    pub fn new(_links: std::collections::HashMap<String, models::Link>, created_at: String, id: String, updated_at: String, address: String, binding: String, cost: i32, dynamic_cost: i32, identity: String, precedence: models::TerminatorPrecedence, router: models::EntityRef, router_id: String, service: models::EntityRef, service_id: String) -> TerminatorDetail {
        TerminatorDetail {
            _links,
            created_at,
            id,
            tags: None,
            updated_at,
            address,
            binding,
            cost,
            dynamic_cost,
            identity,
            precedence,
            router: Box::new(router),
            router_id,
            service: Box::new(service),
            service_id,
        }
    }
}

