/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.51
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerminatorUpdate {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "binding")]
    pub binding: String,
    #[serde(rename = "cost", skip_serializing_if = "Option::is_none")]
    pub cost: Option<i32>,
    #[serde(rename = "precedence", skip_serializing_if = "Option::is_none")]
    pub precedence: Option<models::TerminatorPrecedence>,
    #[serde(rename = "router")]
    pub router: String,
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::Tags>>,
}

impl TerminatorUpdate {
    pub fn new(address: String, binding: String, router: String, service: String) -> TerminatorUpdate {
        TerminatorUpdate {
            address,
            binding,
            cost: None,
            precedence: None,
            router,
            service,
            tags: None,
        }
    }
}

