/*
 * Ziti Edge Management
 *
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.26.52
 * Contact: help@openziti.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotpToken {
    #[serde(rename = "issuedAt")]
    pub issued_at: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl TotpToken {
    pub fn new(issued_at: String, token: String) -> TotpToken {
        TotpToken {
            issued_at,
            token,
        }
    }
}

